name: ROS 2 CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build_and_test:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up ROS 2
        uses: ros-tooling/setup-ros@v0.7
        with:
          required-ros-distributions: humble

      - name: Install required system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            python3-colcon-common-extensions \
            python3-pytest \
            ros-humble-smach \
            ros-humble-geometry-msgs \
            ros-humble-sensor-msgs \
            ros-humble-std-msgs

      - name: Downgrade setuptools to avoid canonicalize_version error
        run: |
          python3 -m pip install --upgrade pip
          python3 -m pip install "setuptools<69"

      - name: Install ROS 2 Python dependencies using rosdep
        run: |
          sudo rosdep init || true
          rosdep update
          rosdep install --from-paths . --ignore-src -r -y

      - name: Build the package
        run: |
          source /opt/ros/humble/setup.bash
          colcon build --packages-select robot_safety_controller

      - name: Run tests
        run: |
          source /opt/ros/humble/setup.bash
          colcon test --packages-select robot_safety_controller

      - name: Show test results
        run: |
          source /opt/ros/humble/setup.bash
          colcon test-result --verbose