name: ROS 2 CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build_and_test:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Debug - Check disk space
        run: df -h

      - name: Install ROS 2 Humble (manual)
        run: |
          # Set up locale
          sudo apt-get update || true
          sudo apt-get install -y locales
          sudo locale-gen en_US en_US.UTF-8
          sudo update-locale LC_ALL=en_US.UTF-8 LANG=en_US.UTF-8
          export LANG=en_US.UTF-8

          # Add ROS 2 repository with retries
          echo "Setting up ROS 2 repository..."
          sudo apt-get install -y curl gnupg2 lsb-release
          
          for i in {1..5}; do
            echo "Attempt $i to setup ROS key..."
            curl -sSL https://raw.githubusercontent.com/ros/rosdistro/master/ros.key | sudo apt-key add - && break || sleep 15
          done
          
          echo "deb [arch=$(dpkg --print-architecture)] http://packages.ros.org/ros2/ubuntu $(lsb_release -cs) main" | sudo tee /etc/apt/sources.list.d/ros2.list > /dev/null

          # Install ROS with retries
          for i in {1..5}; do
            echo "Attempt $i to update apt..."
            sudo apt-get update && break || sleep 15
          done

          sudo apt-get install -y ros-humble-desktop
          source /opt/ros/humble/setup.bash

      - name: Install dependencies
        run: |
          sudo apt-get install -y \
            python3-colcon-common-extensions \
            python3-pytest \
            ros-humble-smach \
            ros-humble-geometry-msgs \
            ros-humble-sensor-msgs \
            ros-humble-std-msgs

      - name: Build package
        run: |
          source /opt/ros/humble/setup.bash
          colcon build --packages-select robot_safety_controller

      - name: Run tests
        run: |
          source /opt/ros/humble/setup.bash
          colcon test --packages-select robot_safety_controller