jobs:
  build-and-test:
    runs-on: ubuntu-latest
    container:
      image: ros:humble
      options: --user root

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install dependencies
        run: |
          apt-get update
          apt-get install -y python3-colcon-common-extensions python3-pip

      - name: Downgrade setuptools to avoid compatibility issue
        run: pip install setuptools==65.5.1

      - name: Build workspace
        run: bash -c "source /opt/ros/humble/setup.bash && colcon build --packages-select robot_safety_controller"

      - name: Run unit tests
        run: bash -c "source /opt/ros/humble/setup.bash && colcon test --packages-select robot_safety_controller && colcon test-result --verbose"