name: ROS 2 CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build_and_test:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Check disk space
        run: df -h

      - name: Set up ROS 2
        uses: ros-tooling/setup-ros@v0.8
        with:
          required-ros-distributions: humble

      - name: Install system dependencies
        run: |
          for i in {1..5}; do
            sudo apt-get update && break || sleep 15
          done
          sudo apt-get install -y \
            python3-colcon-common-extensions \
            python3-pytest \
            ros-humble-smach \
            ros-humble-geometry-msgs \
            ros-humble-sensor-msgs \
            ros-humble-std-msgs

      - name: Build package
        run: |
          source /opt/ros/humble/setup.bash
          colcon build --packages-select robot_safety_controller

      - name: Run tests
        run: |
          source /opt/ros/humble/setup.bash
          colcon test --packages-select robot_safety_controller
          colcon test-result --verbose