name: ROS 2 Python CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up ROS 2 Humble
        uses: ros-tooling/setup-ros@v0.7
        with:
          required-ros-distributions: humble

      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install -y python3-colcon-common-extensions

      - name: Build workspace
        run: |
          source /opt/ros/humble/setup.bash
          colcon build --packages-select robot_safety_controller

      - name: Run tests
        run: |
          source /opt/ros/humble/setup.bash
          colcon test --packages-select robot_safety_controller
          colcon test-result --verbose
